#--------------------------------------------------------------
# HelixCore docker-compose
#--------------------------------------------------------------
version: '3'

#---NETWORKS---------------------------------------------------
networks:
  default:
    external:
      name: common

#---SERVICES---------------------------------------------------
services:
  p4proxy:
    build: ./p4p
    environment:
      P4PORT: ssl:1666
      PORT: ssl:1777
      P4USER: super
      P4PASSWD: Passw0rd
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    privileged: true
    tty: true
    image: p4p
    ports:
      - "1777:1777"
