#--------------------------------------------------------------
# HelixCore docker-compose
#--------------------------------------------------------------
version: '3'

#---NETWORKS---------------------------------------------------
networks:
  default:
    external:
      name: common

#---SERVICES---------------------------------------------------
services:
  p4proxy:
    build: ./p4p
    environment:
      P4TARGET: ssl:127.0.0.1:1666
      P4USER: super
      P4PASSWD: Passw0rd
      P4PORT: ${P4TARGET}
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    privileged: true
    tty: true
    image: p4p

